[package]
name = "server"
version = "0.1.0"
edition = "2021"


[dependencies]
axum = "0.8.1"
tokio = { version = "1", features = ["full"] }
opencv = { version = "0.94.3", features = ["clang-runtime"] }
onnxruntime = "0.0.14"
rocket = "0.5.1"

